# Site settings
title: 上海古贺精工有限公司 - Shanghai Guhe Precision Work Co. Ltd.
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://shghjg.github.io"

sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-compass

# Build settings
markdown: kramdown

images_dir: images
css_dir: css
js_dir: js
fonts_dir: fonts

ch:
  company_name: 上海古贺精工有限公司

en:
  company_name: Shanghai Guhe Precision Work Co. Ltd.
